# Generated by Django 5.1.4 on 2025-07-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
